In [13]:
import pandas_datareader as pdr
pdr.get_data_yahoo('AAPL')

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2010-01-04,30.642857,30.340000,30.490000,30.572857,123432400.0,20.473503
2010-01-05,30.798571,30.464285,30.657143,30.625713,150476200.0,20.508902
2010-01-06,30.747143,30.107143,30.625713,30.138571,138040000.0,20.182680
2010-01-07,30.285715,29.864286,30.250000,30.082857,119282800.0,20.145369
2010-01-08,30.285715,29.865715,30.042856,30.282858,111902700.0,20.279305
2010-01-11,30.428572,29.778572,30.400000,30.015715,115557400.0,20.100410
2010-01-12,29.967142,29.488571,29.884285,29.674286,148614900.0,19.871763
2010-01-13,30.132856,29.157143,29.695715,30.092857,151473000.0,20.152065
2010-01-14,30.065714,29.860001,30.015715,29.918571,108223500.0,20.035355
2010-01-15,30.228571,29.410000,30.132856,29.418571,148516900.0,19.700523
2010-01-19,30.741428,29.605715,29.761429,30.719999,182501900.0,20.572037
2010-01-20,30.792856,29.928572,30.701429,30.247143,153038200.0,20.255390
2010-01-21,30.472857,29.601429,30.297142,29.724285,152038600.0,19.905249
2010-01-22,29.642857,28.165714,29.540001,28.250000,220441900.0,18.917973
2010-01-25,29.242857,28.598572,28.930000,29.010000,266424900.0,19.426920
2010-01-26,30.530001,28.940001,29.421429,29.420000,466777500.0,19.701479
2010-01-27,30.082857,28.504286,29.549999,29.697144,430642100.0,19.887072
2010-01-28,29.357143,28.385714,29.275715,28.469999,293375600.0,19.065300
2010-01-29,28.885714,27.178572,28.725714,27.437143,311488100.0,18.373636
2010-02-01,28.000000,27.328571,27.481428,27.818571,187469100.0,18.629066
2010-02-02,28.045713,27.625713,27.987143,27.980000,174585600.0,18.737165
2010-02-03,28.600000,27.774286,27.881428,28.461428,153832000.0,19.059557
2010-02-04,28.338572,27.367144,28.104286,27.435715,189413000.0,18.372683
2010-02-05,28.000000,27.264286,27.518572,27.922857,212576700.0,18.698900
2010-02-08,28.268572,27.714285,27.955715,27.731428,119567700.0,18.570709
2010-02-09,28.214285,27.821428,28.059999,28.027143,158221700.0,18.768732
2010-02-10,28.085714,27.751429,27.984285,27.874287,92590400.0,18.666370
2010-02-11,28.535715,27.722857,27.840000,28.381428,137586400.0,19.005989
2010-02-12,28.805714,27.928572,28.301428,28.625713,163867200.0,19.169575
2010-02-16,29.098572,28.788572,28.848572,29.057142,135934400.0,19.458488
...,...,...,...,...,...,...
2018-11-20,181.470001,175.509995,178.369995,176.979996,67825200.0,176.979996
2018-11-21,180.270004,176.550003,179.729996,176.779999,31124200.0,176.779999
2018-11-23,176.600006,172.100006,174.940002,172.289993,23624000.0,172.289993
2018-11-26,174.949997,170.259995,174.240005,174.619995,44998500.0,174.619995
2018-11-27,174.770004,170.880005,171.509995,174.240005,41387400.0,174.240005
2018-11-28,181.289993,174.929993,176.729996,180.940002,46062500.0,180.940002
2018-11-29,182.800003,177.699997,182.660004,179.550003,41770000.0,179.550003
2018-11-30,180.330002,177.029999,180.289993,178.580002,39531500.0,178.580002
2018-12-03,184.940002,181.210007,184.460007,184.820007,40802500.0,184.820007
2018-12-04,182.389999,176.270004,180.949997,176.690002,41344300.0,176.690002
2018-12-06,174.779999,170.419998,171.759995,174.720001,43098400.0,174.720001
2018-12-07,174.490005,168.300003,173.490005,168.490005,42281600.0,168.490005
2018-12-10,170.089996,163.330002,165.000000,169.600006,62026000.0,169.600006
2018-12-11,171.789993,167.000000,171.660004,168.630005,47281700.0,168.630005
2018-12-12,171.919998,169.020004,170.399994,169.100006,35627700.0,169.100006
2018-12-13,172.570007,169.550003,170.490005,170.949997,31898600.0,170.949997
2018-12-14,169.080002,165.279999,169.000000,165.479996,40703700.0,165.479996
2018-12-17,168.350006,162.729996,165.449997,163.940002,44287900.0,163.940002
2018-12-18,167.529999,164.389999,165.380005,166.070007,33841500.0,166.070007
2018-12-19,167.449997,159.089996,166.000000,160.889999,49047300.0,160.889999
2018-12-20,162.110001,155.300003,160.399994,156.830002,64773000.0,156.830002
2018-12-21,158.160004,149.630005,156.860001,150.729996,95744600.0,150.729996
2018-12-24,151.550003,146.589996,148.149994,146.830002,37169200.0,146.830002
2018-12-26,157.229996,146.720001,148.300003,157.169998,58582500.0,157.169998
2018-12-27,156.770004,150.070007,155.839996,156.149994,53117100.0,156.149994
2018-12-28,158.520004,154.550003,157.500000,156.229996,42291400.0,156.229996
2018-12-31,159.360001,156.479996,158.529999,157.740005,35003500.0,157.740005
2019-01-02,158.850006,154.229996,154.889999,157.919998,37039700.0,157.919998
2019-01-03,145.720001,142.000000,143.979996,142.190002,91244100.0,142.190002
2019-01-04,146.080002,143.800003,144.529999,146.059998,15796632.0,146.059998

In [19]:
import pandas_datareader.data as web
import datetime    

start = datetime.datetime(2018, 1, 1)
end = datetime.datetime(2019, 1, 27)
df = web.DataReader("GOOGL", 'yahoo', start, end)

dates =[]
for x in range(len(df)):
    newdate = str(df.index[x])
    newdate = newdate[0:10]
    dates.append(newdate)

df['dates'] = dates

print(df.head())
print(df.tail())

                   High          Low         Open        Close   Volume  \
Date
2018-01-02  1075.979980  1053.020020  1053.020020  1073.209961  1588300
2018-01-03  1096.099976  1073.430054  1073.930054  1091.520020  1565900
2018-01-04  1104.079956  1094.260010  1097.089966  1095.760010  1302600
2018-01-05  1113.579956  1101.800049  1103.449951  1110.290039  1512500
2018-01-08  1119.160034  1110.000000  1111.000000  1114.209961  1232200

              Adj Close       dates
Date
2018-01-02  1073.209961  2018-01-02
2018-01-03  1091.520020  2018-01-03
2018-01-04  1095.760010  2018-01-04
2018-01-05  1110.290039  2018-01-05
2018-01-08  1114.209961  2018-01-08
                   High          Low         Open        Close   Volume  \
Date
2018-12-28  1064.229980  1042.000000  1059.500000  1046.680054  1719900
2018-12-31  1062.989990  1033.040039  1057.829956  1044.959961  1655500
2019-01-02  1060.790039  1025.280029  1027.199951  1054.680054  1593400
2019-01-03  1066.260010  1022.369995  1050.670044  1025.469971  2096000
2019-01-04  1057.489990  1036.859985  1042.560059  1057.109985   362388

              Adj Close       dates
Date
2018-12-28  1046.680054  2018-12-28
2018-12-31  1044.959961  2018-12-31
2019-01-02  1054.680054  2019-01-02
2019-01-03  1025.469971  2019-01-03
2019-01-04  1057.109985  2019-01-04